name: "Build ISO"
on:
  pull_request:
  push:
jobs:
  iso:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: aarch64
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-platforms = aarch64-linux arm-linux
    - name: Install nixos-generators
      run: nix-env -i nixos-generators -f '<nixpkgs>'
    - name: Generate ISO
      run: nixos-generate -f iso -c configuration.nix -I nixpkgs=channel:nixos-unstable --system aarch64-linux
    # TODO(negz): I believe nixos-generate will echo the ISO path.
    # - name: Publish ISO to GitHub
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: _output/**