name: "Build ISO"
on:
  pull_request:
  push:
jobs:
  iso:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install nixos-generators
      run: nix-env -i nixos-generators -f '<nixpkgs>'
    - name: Generate ISO
      run: nixos-generate -f iso -c configuration.nix -I nixpkgs=channel:nixos-unstable --system aarch64
    # TODO(negz): I believe nixos-generate will echo the ISO path.
    # - name: Publish ISO to GitHub
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: _output/**